# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string
#  publish    :string
#  isbn       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BooksController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Book. As you add validations to Book, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      title: Faker::Book.title,
      publish: Faker::Book.publisher,
      isbn: Faker::Code.isbn
    }
  end

  let(:invalid_attributes) do
    {
      title: '',
      publish: Faker::Book.publisher,
      isbn: Faker::Code.isbn
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BooksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'assigns all books as @books' do
      book = Book.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:books)).to eq([book])
    end
  end

  describe 'GET #show' do
    it 'assigns the requested book as @book' do
      book = Book.create! valid_attributes
      get :show, { id: book.to_param }, valid_session
      expect(assigns(:book)).to eq(book)
    end
  end

  describe 'GET #new' do
    it 'assigns a new book as @book' do
      get :new, {}, valid_session
      expect(assigns(:book)).to be_a_new(Book)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested book as @book' do
      book = Book.create! valid_attributes
      get :edit, { id: book.to_param }, valid_session
      expect(assigns(:book)).to eq(book)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new Book' do
        expect do
          post :create, { book: valid_attributes }, valid_session
        end.to change(Book, :count).by(1)
      end

      it 'assigns a newly created book as @book' do
        post :create, { book: valid_attributes }, valid_session
        expect(assigns(:book)).to be_a(Book)
        expect(assigns(:book)).to be_persisted
      end

      it 'redirects to the created book' do
        post :create, { book: valid_attributes }, valid_session
        expect(response).to redirect_to(Book.last)
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved book as @book' do
        post :create, { book: invalid_attributes }, valid_session
        expect(assigns(:book)).to be_a_new(Book)
      end

      it "re-renders the 'new' template" do
        post :create, { book: invalid_attributes }, valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        {
          title: Faker::Book.title,
          publish: Faker::Book.publisher,
          isbn: Faker::Code.isbn
        }
      end

      it 'updates the requested book' do
        book = Book.create! valid_attributes
        put :update, { id: book.to_param, book: new_attributes }, valid_session
        book.reload
        new_attributes.each { |x| expect(book[x.first]).to eq x.last }
      end

      it 'assigns the requested book as @book' do
        book = Book.create! valid_attributes
        put :update, { id: book.to_param, book: valid_attributes },
            valid_session

        expect(assigns(:book)).to eq(book)
      end

      it 'redirects to the book' do
        book = Book.create! valid_attributes
        put :update, { id: book.to_param, book: valid_attributes },
            valid_session

        expect(response).to redirect_to(book)
      end
    end

    context 'with invalid params' do
      it 'assigns the book as @book' do
        book = Book.create! valid_attributes
        put :update, { id: book.to_param, book: invalid_attributes },
            valid_session

        expect(assigns(:book)).to eq(book)
      end

      it "re-renders the 'edit' template" do
        book = Book.create! valid_attributes
        put :update, { id: book.to_param, book: invalid_attributes },
            valid_session

        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested book' do
      book = Book.create! valid_attributes
      expect do
        delete :destroy, { id: book.to_param }, valid_session
      end.to change(Book, :count).by(-1)
    end

    it 'redirects to the books list' do
      book = Book.create! valid_attributes
      delete :destroy, { id: book.to_param }, valid_session
      expect(response).to redirect_to(books_url)
    end
  end
end
